spring:
  application:
    name: OllamaDemo1
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3
          temperature: 0.7
          top-p: 0.9
          max-tokens: 1000
      embedding:
        options:
          model: gemma3

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

ollama:
  api-url: http://localhost:11434
  model: gemma3